"""Provider configuration package."""

from __future__ import annotations

from .loader import list_providers, load_provider_config, load_provider_config_data
from .models import (
    AddressConfig,
    CAAMatchRule,
    CAAConfig,
    CAARecord,
    CNAMEMatchRule,
    CNAMEConfig,
    DKIMRequired,
    DKIMConfig,
    DMARCOptional,
    DMARCConfig,
    DMARCRequired,
    DMARCSettings,
    MXConfig,
    MXNegativePolicy,
    MXNegativeRules,
    MXRecord,
    ProviderConfig,
    ProviderVariable,
    PTRConfig,
    SPFOptional,
    SPFConfig,
    SPFRequired,
    SRVMatchRule,
    SRVConfig,
    SRVRecord,
    TLSAMatchRule,
    TLSAConfig,
    TLSARecord,
    TXTConfig,
    TXTSettings,
    ValuesMatchRule,
)
from .resolve import resolve_provider_config
from .utils import CONFIG_DIR_NAME, PROVIDER_DIR_NAME, TEMPLATE_DIR_NAME, external_config_dirs

__all__ = [
    "AddressConfig",
    "CAAMatchRule",
    "CAAConfig",
    "CAARecord",
    "CNAMEMatchRule",
    "CNAMEConfig",
    "CONFIG_DIR_NAME",
    "DKIMRequired",
    "DKIMConfig",
    "DMARCOptional",
    "DMARCConfig",
    "DMARCRequired",
    "DMARCSettings",
    "MXConfig",
    "MXNegativePolicy",
    "MXNegativeRules",
    "MXRecord",
    "PROVIDER_DIR_NAME",
    "ProviderConfig",
    "ProviderVariable",
    "PTRConfig",
    "SPFOptional",
    "SPFConfig",
    "SPFRequired",
    "SRVMatchRule",
    "SRVConfig",
    "SRVRecord",
    "TLSAMatchRule",
    "TLSAConfig",
    "TLSARecord",
    "TEMPLATE_DIR_NAME",
    "TXTConfig",
    "TXTSettings",
    "ValuesMatchRule",
    "external_config_dirs",
    "list_providers",
    "load_provider_config",
    "load_provider_config_data",
    "resolve_provider_config",
]
